import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";


const raleway = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${raleway.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
