import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";


const raleway = Raleway({
  variable: "--font-raleway-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"], // All weights you'll need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${raleway.variable} antialiased`}
      >
                <NextIntlClientProvider>{children}</NextIntlClientProvider>

      </body>
    </html>
  );
}
